### ISSUE TITLE
Latest seed-via-docker.sh fails

### ISSUE THREAD

**Issue by roggenkamps** [INCATools/ontology-development-kit#824]
My teammate and I have tried to get the latest version of ODK to work on both Linux and Mac, but it fails.  I'm using a Mac running 11.7.3 with Docker Desktop 4.16.2 installed.  I downloaded the latest version of the `seed-via-docker.sh` script but it fails as shown below.  I thought the problem might be related to setting the ODK_VERSION environment variable as it is mentioned in the traceback, so I set it to 'v1.4', the latest tag in GitHub, but that makes no differeence.

```
skro232@mac01:OBO-odk$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
skro232@mac01:OBO-odk$ cat seed-via-docker.sh 
#!/bin/sh

set -e

echo "This script only works with ODK 1.3.2 and later. For ODK 1.3.1 or earlier, use https://raw.githubusercontent.com/INCATools/ontology-development-kit/v1.3.1/seed-via-docker.sh"

ODK_IMAGE=${ODK_IMAGE:-odkfull}
ODK_TAG=${ODK_TAG:-latest}
ODK_GITNAME=${ODK_GITNAME:-$(git config --get user.name)}
ODK_GITEMAIL=${ODK_GITEMAIL:-$(git config --get user.email)}

docker run -v $PWD:/work -w /work --rm obolibrary/$ODK_IMAGE:$ODK_TAG /tools/odk.py seed --gitname "$ODK_GITNAME" --gitemail "$ODK_GITEMAIL" "$@"
skro232@mac01:OBO-odk$ ./seed-via-docker.sh 
This script only works with ODK 1.3.2 and later. For ODK 1.3.1 or earlier, use https://raw.githubusercontent.com/INCATools/ontology-development-kit/v1.3.1/seed-via-docker.sh
INFO:root:  Copying: /tools/templates/CONTRIBUTING.md.jinja2 -> target/None/CONTRIBUTING.md.jinja2
INFO:root:  Copying: /tools/templates/.gitignore.jinja2 -> target/None/.gitignore.jinja2
INFO:root:  Copying: /tools/templates/README.md.jinja2 -> target/None/README.md.jinja2
INFO:root:  Copying: /tools/templates/issue_template.md.jinja2 -> target/None/issue_template.md.jinja2
INFO:root:  Copying: /tools/templates/CODE_OF_CONDUCT.md -> target/None/CODE_OF_CONDUCT.md
INFO:root:  Copying: /tools/templates/_dynamic_files.jinja2 -> target/None/_dynamic_files.jinja2
INFO:root:Applying templates
INFO:root:  Compiling: /tools/templates/CONTRIBUTING.md.jinja2 -> target/None/CONTRIBUTING.md
Traceback (most recent call last):
  File "/tools/odk.py", line 976, in <module>
    cli()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tools/odk.py", line 910, in seed
    s.write(mg.generate(srcf))
  File "/tools/odk.py", line 682, in generate
    return template.render( project = self.context.project, env = {"ODK_VERSION": os.getenv("ODK_VERSION")})
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.10/dist-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'None' has no attribute 'upper'
skro232@mac01:OBO-odk$ git config user.name
Steve Roggenkamp
skro232@mac01:OBO-odk$ git config user.email
roggenkamps@acm.org
skro232@mac01:OBO-odk$ export ODK_VERSION=v1.4
skro232@mac01:OBO-odk$ ./seed-via-docker.sh 
This script only works with ODK 1.3.2 and later. For ODK 1.3.1 or earlier, use https://raw.githubusercontent.com/INCATools/ontology-development-kit/v1.3.1/seed-via-docker.sh
INFO:root:  Copying: /tools/templates/CONTRIBUTING.md.jinja2 -> target/None/CONTRIBUTING.md.jinja2
INFO:root:  Copying: /tools/templates/.gitignore.jinja2 -> target/None/.gitignore.jinja2
INFO:root:  Copying: /tools/templates/README.md.jinja2 -> target/None/README.md.jinja2
INFO:root:  Copying: /tools/templates/issue_template.md.jinja2 -> target/None/issue_template.md.jinja2
INFO:root:  Copying: /tools/templates/CODE_OF_CONDUCT.md -> target/None/CODE_OF_CONDUCT.md
INFO:root:  Copying: /tools/templates/_dynamic_files.jinja2 -> target/None/_dynamic_files.jinja2
INFO:root:Applying templates
INFO:root:  Compiling: /tools/templates/CONTRIBUTING.md.jinja2 -> target/None/CONTRIBUTING.md
Traceback (most recent call last):
  File "/tools/odk.py", line 976, in <module>
    cli()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tools/odk.py", line 910, in seed
    s.write(mg.generate(srcf))
  File "/tools/odk.py", line 682, in generate
    return template.render( project = self.context.project, env = {"ODK_VERSION": os.getenv("ODK_VERSION")})
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.10/dist-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'None' has no attribute 'upper'
skro232@mac01:OBO-odk$ 
```

**Comment by matentzn** [comment]
Thank you @roggenkamps  for reaching out. I tried this, just to double-check: 

```
 sh seed-via-docker.sh -C tests/test-sssom.yaml 
```

Just to be 100% on the same page, can you run

```
docker pull obolibrary/odkfull
```

followed by

```
./seed-via-docker.sh -C thenameofyourconfig.yaml
```

? I cant see the name of your config file in the above message, maybe that is the problem?

**Comment by roggenkamps** [comment]
Yes, that's it.  Thanks much.
